name = "portfolio"
compatibility_date = "2026-06-20"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[build]
command = "pnpm run build"

[assets]
directory = ".open-next/assets"

workers_dev = false
preview_urls = false